### ISSUE TITLE
Bug in multiworld

### ISSUE THREAD

**Issue by rokibot009** [Vecnavium/FloatingTextCreator#5] opened 2021-08-24 14:01 UTC
the plugin is working but there is a bug issue in multiworld..

Can u fix it?
btw.. ur plugin is cool

**Comment by Vecnavium** [comment] 2021-08-24 14:25
Closing this issue.
Please respond to the issue template so it's more detailed so I know why the issue is created and what the issue is, and I doubt this is a FloatingTextCreator issue it's more than likely MultiWorld or another plugin causing this

**Closed as completed by Vecnavium** 2021-08-24 14:25 UTC
